### ISSUE TITLE
Array indexOf returns undefined

### ISSUE THREAD

**Issue by jesusvazquez** [sn-developer/Xplore#5]
Hello, 

I was trying out Xplore a bit and I think I found a small bug. 

**Code**:
```
var array = [1,2,3,4];
var index = array.indexOf(2);
gs.log(index);
```
**Output**:
```
09:20:26.937: undefined
Type	 undefined
String	""
```

Cheers, 
Jesús.

**Comment by jneale** [comment]
Hey Jesús,

Yeah, that's actually not a bug with Xplore but an unsupported function in ECMA3 which is what versions of ServiceNow < Helsinki run. They recently updated it for Helsinki to run ECMA5 which includes indexOf on the Array prototype. 

You can find the polyfill on https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Array/indexOf

Cheers
James
